# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         smtm
version:      1.6.8
version_from: smtm
installdirs:  site
requires:
    Date::Manip:                   5
    Finance::YahooQuote:           0.2
    HTML::Parser:                  2.2
    LWP::UserAgent:                1.23
    MIME::Base64:                  2.12
    Tk:                            800.015
    Tk::PNG:                       2.005

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
